/* ============================================================================
   SEO — one source of truth for the domain, the shared metadata defaults, and
   the structured data builders.
   ----------------------------------------------------------------------------
   Every schema here is assembled from content that actually exists on the
   page. Nothing describes the business in ways the site does not already
   state: no AggregateRating, no Review, no Offer, no invented address or
   social profiles. Fabricated markup of that kind is a structured-data spam
   violation and gets rich results revoked, which is a worse outcome than not
   having them. `sameAs`, ratings and contact points can be filled in once
   there are real values to point at.
   ========================================================================== */

export const SITE = {
  url: "https://www.fair-play.co",
  name: "FairPlay",
  locale: "en_IN",
  language: "en-IN",
  title: "FairPlay Official Website – Online Sports Betting & Online Casino in India",
  description:
    "FairPlay brings Online Sports Betting and Online Casino India together on one platform — cricket, football, tennis, kabaddi, esports, live dealer tables and the FairPlay App.",
};

export const absolute = (path = "/") => new URL(path, SITE.url).toString();

/* The card generated by app/opengraph-image.js, addressable as a route. */
export const OG_IMAGE = "/opengraph-image";

/* ------------------------------------------------------------------ routes
   The single list the sitemap, the breadcrumbs and the footer nav can all be
   derived from, so a new page cannot be added to one and missed by another.
   `changeFrequency` and `priority` are hints only — Google ignores them — but
   they cost nothing and other crawlers still read them. */
export const ROUTES = [
  { path: "/", name: "Home", priority: 1, changeFrequency: "weekly" },
  { path: "/cricket-betting", name: "Cricket betting", priority: 0.9, changeFrequency: "weekly" },
  { path: "/football-betting", name: "Football betting", priority: 0.9, changeFrequency: "weekly" },
  { path: "/tennis-betting", name: "Tennis betting", priority: 0.8, changeFrequency: "weekly" },
  { path: "/basketball-betting", name: "Basketball betting", priority: 0.8, changeFrequency: "weekly" },
  { path: "/casino", name: "Casino", priority: 0.9, changeFrequency: "weekly" },
  { path: "/betting-odds", name: "Betting odds", priority: 0.8, changeFrequency: "monthly" },
  { path: "/faq", name: "FAQ", priority: 0.7, changeFrequency: "monthly" },
  { path: "/about", name: "About", priority: 0.6, changeFrequency: "monthly" },
];

/* --------------------------------------------------------------- metadata
   Builds the per-page Metadata object so every route gets a canonical, an
   Open Graph entry and a Twitter card without restating the same shape nine
   times. Canonicals are the important part here: the site is reachable at
   several host spellings and every marketing link carries a hash, so without
   one Google is free to pick its own preferred URL. */
export function pageMeta({ title, description, path, keywords }) {
  return {
    title,
    description,
    ...(keywords ? { keywords } : {}),
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE.name,
      locale: SITE.locale,
      type: "website",
      /* Stated explicitly rather than left to app/opengraph-image.js. That
         file convention only decorates the segment it sits in, and declaring
         `openGraph` here replaces the parent object wholesale — between them,
         every inner page was shipping with no og:image at all. */
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: SITE.title }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE],
    },
  };
}

/* ---------------------------------------------------------- structured data */

export function organizationSchema() {
  return {
    "@type": "Organization",
    "@id": `${SITE.url}/#organization`,
    name: SITE.name,
    url: SITE.url,
    logo: {
      "@type": "ImageObject",
      url: absolute("/fairplay-logo.png"),
      width: 122,
      height: 50,
    },
  };
}

export function websiteSchema() {
  return {
    "@type": "WebSite",
    "@id": `${SITE.url}/#website`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    inLanguage: SITE.language,
    publisher: { "@id": `${SITE.url}/#organization` },
  };
}

/* `trail` is [{ name, path }], home first. A single-entry trail is skipped —
   a breadcrumb that only contains the page itself tells a crawler nothing. */
export function breadcrumbSchema(trail) {
  if (!trail || trail.length < 2) return null;
  return {
    "@type": "BreadcrumbList",
    "@id": `${absolute(trail[trail.length - 1].path)}#breadcrumb`,
    itemListElement: trail.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: absolute(crumb.path),
    })),
  };
}

/* `faqs` is the same [{ q, a }] shape the Accordion renders, so the markup and
   the visible page can never drift apart — which is itself a Google
   requirement for FAQ rich results. */
export function faqSchema(faqs, path) {
  if (!faqs?.length) return null;
  return {
    "@type": "FAQPage",
    "@id": `${absolute(path)}#faq`,
    mainEntity: faqs.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  };
}

export function webPageSchema({ title, description, path, breadcrumb }) {
  return {
    "@type": "WebPage",
    "@id": `${absolute(path)}#webpage`,
    url: absolute(path),
    name: title,
    description,
    inLanguage: SITE.language,
    isPartOf: { "@id": `${SITE.url}/#website` },
    ...(breadcrumb ? { breadcrumb: { "@id": breadcrumb["@id"] } } : {}),
  };
}

/* One @graph per page rather than several loose blocks: it lets the nodes
   reference each other by @id, so the page, the site and the organisation are
   understood as one connected entity instead of three unrelated ones. */
export function graph(...nodes) {
  return { "@context": "https://schema.org", "@graph": nodes.filter(Boolean) };
}

/* `</script>` inside a JSON string would close the tag early, so the escape is
   required even though every value here is authored by us. */
export function JsonLd({ schema }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }}
    />
  );
}
